version: '3'
services:

    nginx_app:

        image: nginx:latest
        depends_on:
        - flask_app
        volumes:
        - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
        - 8090:80
        networks:
        - backend


    flask_app:

        image: flaski_name
        ports:
        - 8081:5000
        expose:
        - 5000
        networks:
        - backend


networks:
    backend: