name: cd_action

on:
  workflow_run:
    workflows: ["cd_action"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull ${{ secrets.DOCKER_HUB_USER }}/sessions-project:githubactions
    - name: Delete old container
      run: sudo docker rm -f sessions-project-container || true
    - name: Run container
      run: sudo docker run -d -p --name sessions-project-container ${{ secrets.DOCKER_HUB_USER }}/sessions-project:githubactions

      
  
